import os
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# Notification Configuration
NOTIFICATION_CONFIG = {
    'method': 'email',  # 可选值: 'email', 'wechat', 'both'
    'wechat_receiver': os.getenv('TRENDS_WECHAT_RECEIVER', ''),  # 微信接收者的备注名或微信号
}

# Email Configuration
EMAIL_CONFIG = {
    'smtp_server': os.getenv('TRENDS_SMTP_SERVER', 'smtp.gmail.com'),
    'smtp_port': int(os.getenv('TRENDS_SMTP_PORT', '587')),
    'sender_email': os.getenv('TRENDS_SENDER_EMAIL', ''),
    'sender_password': os.getenv('TRENDS_SENDER_PASSWORD', ''),
    'recipient_email': os.getenv('TRENDS_RECIPIENT_EMAIL', '')
}

# Keywords to monitor
KEYWORDS = [
    "ai agent",
    "ai arena",
    "ai app",
    "ai apply",
    "ai assistant",
    "ai agent skills",
    "ai api",
    "ai art",
    "ai art generator",
    "ai avatar",
    "ai benchmark",
    "ai bubble",
    "ai browser",
    "ai background remover",
    "ai bot",
    "ai baby",
    "ai benchmark ranking",
    "ai banana",
    "ai box",
    "ai bubble burst",
    "ai checker",
    "ai chat",
    "ai check",
    "ai coding",
    "ai chatbot",
    "ai checker free",
    "ai claude",
    "ai conference deadlines",
    "ai china",
    "ai courses",
    "ai detector",
    "ai detector free",
    "ai detection",
    "ai dungeon",
    "ai deadlines",
    "ai design",
    "ai detection tool",
    "ai detector turnitin",
    "ai data centers",
    "ai detector chinese",
    "ai engineer",
    "ai elements",
    "ai editor",
    "ai edge gallery",
    "ai exporter",
    "ai edit photo",
    "ai enhancer",
    "ai education",
    "ai emoji",
    "ai ethics",
    "ai face swap",
    "ai for science",
    "ai free",
    "ai for everyone",
    "ai fiesta",
    "ai for research",
    "ai for good",
    "ai factory",
    "ai free image generator",
    "ai flow",
    "ai gemini",
    "ai google",
    "ai generator",
    "ai glasses",
    "ai generated images",
    "ai gallery",
    "ai google studio",
    "ai generated video",
    "ai gateway",
    "ai game",
    "ai humanizer",
    "ai humanizer free",
    "ai harness",
    "ai hallucination",
    "ai hub",
    "ai hedge fund",
    "ai help",
    "ai hairstyle",
    "ai history",
    "ai hardware",
    "ai image generator",
    "ai image generator free",
    "ai infra",
    "ai image editor",
    "ai image",
    "ai image detector",
    "ai ide",
    "ai icon",
    "ai image upscaler",
    "ai infrastructure",
    "ai jobs",
    "ai judge movie",
    "ai job loss",
    "ai journal",
    "ai jesus",
    "ai jiang shan geng ai mei ren lyrics",
    "ai jason",
    "ai job replacement",
    "al jazeera",
    "ai jiu tcm",
    "ai knowledge base",
    "ai keyboard",
    "ai kimi",
    "ai kissing generator",
    "ai kit",
    "ai kanban",
    "ai kissing video generator",
    "ai ka full form",
    "ai kya hai",
    "ai kundali",
    "ai logo generator",
    "ai logo",
    "ai lab",
    "ai leaderboard",
    "ai logo maker",
    "ai logo design",
    "ai limit",
    "ai learning",
    "ai literacy",
    "ai llm ranking",
    "ai mode",
    "ai mode google",
    "ai model",
    "ai music generator",
    "ai model ranking",
    "ai music",
    "ai max 395",
    "ai movie",
    "ai meaning",
    "ai music generator free",
    "ai news",
    "ai native",
    "ai note taker",
    "ai nas",
    "ai ni yi wan nian lyrics",
    "ai ni yi wan nian",
    "ai note",
    "ai newsletter",
    "ai news today",
    "ai notebook",
    "ai overview",
    "ai open",
    "ai or not",
    "ai os",
    "ai ocr",
    "aiops",
    "ai openclaw",
    "ai overwatch act",
    "ai or human",
    "ai overview google",
    "ai ppt",
    "ai photo editor",
    "ai photo generator",
    "ai picture generator",
    "ai ppt maker",
    "ai prompt",
    "ai ppt generator",
    "ai presentation maker",
    "ai photo",
    "ai pro",
    "ai quests",
    "ai qing",
    "ai quant",
    "ai quiz generator",
    "iqiyi",
    "ai quests google",
    "ai quotes",
    "ai question",
    "ai question answer",
    "ai quality enhancer",
    "ai ranking",
    "ai robot",
    "ai research",
    "ai remover",
    "ai review",
    "ai rate",
    "ai remove background",
    "ai reader",
    "ai rag",
    "ai remove watermark",
    "ai studio",
    "ai studio google",
    "ai skills",
    "ai search",
    "ai short",
    "ai slop",
    "ai sdk",
    "ai song generator",
    "ai studio gemini",
    "ai stock",
    "ai translator",
    "ai tools",
    "ai text detector",
    "ai token",
    "ai test",
    "ai toolkit",
    "ai trading",
    "ai timeline",
    "ai terminal",
    "ai tester",
    "ai upscaler",
    "ai ui design",
    "ai undetect",
    "ai ui",
    "ai upscale image",
    "ai ultra",
    "ai usage",
    "ai ugc",
    "ai unipaper",
    "ai uses water",
    "ai video generator",
    "ai video",
    "ai video generator free",
    "ai video maker",
    "ai voice generator",
    "ai video editor",
    "ai voice",
    "ai voice generator free",
    "ai video editing",
    "ai vocal remover",
    "ai weiwei",
    "ai watermark remover",
    "ai workflow",
    "ai writing detector",
    "ai website builder",
    "ai website",
    "ai writing",
    "ai words",
    "ai writer",
    "ai wo bie zou lyrics",
    "ai x",
    "ai xiang sui lyrics",
    "ai xiang sui chords",
    "aixploria",
    "ai xapo snokonoko (mixed)",
    "ai xploria.com",
    "ai xapo",
    "ai xxxtentacion",
    "ai yi fan",
    "ai yi fang",
    "ai ya ai ya lyrics",
    "ai yi ge ren hao nan lyrics",
    "ai youtube video summarizer",
    "ai yazawa books",
    "ai youtube",
    "ai yu jelly",
    "ai youtube thumbnail generator",
    "ai youtube summary",
    "ai zero",
    "ai zen me le lyrics",
    "ai zero gpt",
    "ai z",
    "ai zero detector",
    "ai zoom",
    "ai zoom note taker",
    "ai zolo",
    "ai zi crispy pastry",
    "amizone",
]


# Trends Query Configuration
TRENDS_CONFIG = {
    'timeframe': 'last-3-d',  # 可选值: now 1-d, now 7-d, now 30-d, now 90-d, today 12-m, 
                            # last-2-d, last-3-d 或者 "2024-01-01 2024-01-31"
    'geo': '',  # 地区代码，例如: 'US' 表示美国, 'CN' 表示中国, '' 表示全球
}

# Rate Limiting Configuration
RATE_LIMIT_CONFIG = {
    'max_retries': 3,
    'min_delay_between_queries': 10,  # 最小延迟10秒
    'max_delay_between_queries': 20,  # 最大延迟20秒
    'batch_size': 5,  # 每批处理的关键词数量
    'batch_interval': 300,  # 批次间隔时间（秒）
}

# Schedule Configuration
SCHEDULE_CONFIG = {
    'hour': 0,                     # 计划执行的小时（0-23），UTC 0:00 = 北京时间 8:00
    'minute': 0,                  # 计划执行的分钟（0-59）
    'random_delay_minutes': 15   # 随机延迟的最大分钟数（可选）
}

# Monitoring Configuration
MONITOR_CONFIG = {
    'rising_threshold': 500,  # 高增长趋势阈值
}

# Logging Configuration
LOGGING_CONFIG = {
    'log_file': 'trends_monitor.log',
    'level': 'INFO',
    'format': '%(asctime)s - %(levelname)s - %(message)s'
}

# Data Storage Configuration
STORAGE_CONFIG = {
    'data_dir_prefix': 'data_',  # 数据目录前缀
    'report_filename_prefix': 'daily_report_',  # 报告文件名前缀
    'json_filename_prefix': 'related_queries_'  # JSON文件名前缀
} 
